### ISSUE TITLE
FAILED TO PARSE LUA

### ISSUE THREAD

**Issue by MyGitHub5** [vysheng/tdbot#4]
[clilua.cpp:148][!Td]	FAILED TO PARSE LUA: [Error : 0 : Can't parse "9.2233720368548e+18" as number]

```
tdbot_function ({
	    ["@type"] = "getChats",
	    offset_order = 2^63 - 1,
	    offset_chat_id = 0,
	    limit = 20
  	}, cb, cmd)

```
on: Tdlib > v1.1.1

this error happens with more methods.... like: getSupergroup

**Comment by MyGitHub5** [comment]
and please add if happens error still its call to callback...
Please add "postpone" function it's very useful...
Thanks, amazing work!

**Comment by rizaumami** [comment]
@Mygihub0 
Try `9223372036854775807` for `offset_order`.

**Comment by MyGitHub5** [comment]
```
tdbot_function ({
	    ["@type"] = "getChats",
	    offset_order = 9223372036854775807,
	    offset_chat_id = 0,
	    limit = 20
  	}, cb, cmd)
```

[clilua.cpp:148][!Td]	FAILED TO PARSE LUA: [Error : 0 : Can't parse "9.22337203685478e+18" as number]

same error...

**Comment by MyGitHub5** [comment]
```
local _type_ = "@type"
function send_msg(chat_id, text, parse)
    assert(tdbot_function({
    	[_type_] = "sendMessage",
    	chat_id = chat_id,
    	reply_to_message_id = 0,
    	disable_notification = 0,
    	from_background = 1,
    	reply_markup = nil,
    	input_message_content = {
    		[_type_] = "inputMessageText",
    		text = {
			    [_type_] = "formattedText",
			    text = text,
			    entities = {}
			},
    		disable_web_page_preview = 1,
    		clear_draft = 0,
    		parse_mode = getParse(parse)
    	}
    }, dl_cb, nil))

end

```
this work good !

the error happens with methods "getChats" "getSupergroup"

**Comment by rizaumami** [comment]
`getChats` and `getSupergroup` just working on my test.
Try these:

- `getChats`

  ```lua
  assert (tdbot_function ({
    ["@type"] = 'getChats',
    offset_order = '9223372036854775807',
    offset_chat_id = 0,
    limit = 20
  }, dl_cb, data))
  ```

- `getSupergroup`

  ```lua
  assert (tdbot_function ({
    ["@type"] = 'getSupergroup',
    supergroup_id = chat_id
  }, dl_cb, data))
  ```

Test more thouroughly to make sure the fault is not in your code, then raise an issue.

**Comment by MyGitHub5** [comment]
Thanks!
now "getChats" its work!
but "getSupergroup" still not working...

```
local _print_ = true
local _type_ = "@type"
function getChat(chat_id, cb, cmd)
    if chat_id and tostring(chat_id):match("^%-100") then 
	    if _print_ then print("~~~ getSupergroup ~~~", type(chat_id), chat_id) end 
	    tdbot_function ({
    	        [_type_] = "getSupergroup",
    	        supergroup_id = chat_id
	    }, cb or dl_cb, cmd)
    else
	    if _print_ then print("~~~ getChat ~~~") end 
	    tdbot_function ({
    	        [_type_] = "getChat",
    	        chat_id = chat_id
	    }, cb or dl_cb, cmd)
    end
end
```

output: ~~~ getSupergroup ~~~   string  -100----------
log: [clilua.cpp:148][!Td]	FAILED TO PARSE LUA: [Error : 0 : Can't parse "-100---------" as number]

i'm testing with tonumber() and tostring() but it didn't help...

**Comment by MyGitHub5** [comment]
Thanks!
now "getChats" its work!
but "getSupergroup" still not working...

```
local _print_ = true
local _type_ = "@type"
function getChat(chat_id, cb, cmd)
    if chat_id and tostring(chat_id):match("^%-100") then 
	    if _print_ then print("~~~ getSupergroup ~~~", type(chat_id), chat_id) end 
	    tdbot_function ({
    	        [_type_] = "getSupergroup",
    	        supergroup_id = chat_id
	    }, cb or dl_cb, cmd)
    else
	    if _print_ then print("~~~ getChat ~~~") end 
	    tdbot_function ({
    	        [_type_] = "getChat",
    	        chat_id = chat_id
	    }, cb or dl_cb, cmd)
    end
end
```

output: ~~~ getSupergroup ~~~   string  -100----------
log: [clilua.cpp:148][!Td]	FAILED TO PARSE LUA: [Error : 0 : Can't parse "-100---------" as number]

i'm testing with tonumber() and tostring() but it didn't help...

edit: OK i found the problem...

```
tdbot_function ({
    	        [_type_] = "getSupergroup",
    	        supergroup_id = chat_id:match("^%-100(.+)$")
	    }, cb or dl_cb, cmd)
```
you need to remove "-100" from id...

**Comment by MyGitHub5** [comment]
and please add if happens error still its call to callback...
Please add "postpone" function it's very useful...
Thanks, amazing work!

**Comment by MyGitHub5** [comment]
[clilua.cpp:148][!Td]    FAILED TO PARSE LUA: [Error : 0 : Expected array, got JsonObject]

```
assert(tdbot_function({
    	[_type_] = "sendMessage",
    	chat_id = chat_id,
    	reply_to_message_id = 0,
    	disable_notification = 0,
    	from_background = 1,
    	reply_markup = nil,
    	input_message_content = {
    		[_type_] = "inputMessageText",
    		text = {
			    [_type_] = "formattedText",
			    text = text,
			    entities = {
                                        [0] = {
						offset = 0,
						[_type_] = "textEntity"
						type = {
							[_type_] = "textEntityTypeBold"
						},
						length = 9
					},
					[1] = {
						offset = 34,
						[_type_] = "textEntity",
						type = {
							[_type_] = "textEntityTypeItalic"
						},
						length = 11
					},
					[2] = {
						offset = 10,
						[_type_] = "textEntity",
						type = {
							[_type_] = "textEntityTypeCode"
						},
						length = 23
					}
				}
			},
    		disable_web_page_preview = 1,
    		clear_draft = 0,
    	}
    }, dl_cb, nil))
```
on: Tdlib > v1.1.1

if i use just 1 entities it's work...
like this...

```
entities = {
					[0] = {
						offset = 0,
						[_type_] = "textEntity"
						type = {
							[_type_] = "textEntityTypeBold"
						},
						length = 9
					}
```

more than one it's faild...

**Comment by IRGC** [comment]
why creator of this project never reply?

**Comment by IRGC** [comment]
@vysheng hey bro

**Comment by rizaumami** [comment]
Because he has a life, and this issue is not important.

**Comment by MyGitHub5** [comment]
postpone function it's very important....

**Comment by MyGitHub5** [comment]
I found the problem.
Have the content in the table will be in order from 0 and up and in lua you can't fix it because the initial value in the table is 1 so need to fix it to be in order from 1 and up...

```
entities = {
  [0] = {some data},
  [1] = {some data}
}
```
this work 👆

```
entities = {
  [1] = {some data},
  [0] = {some data}
}
```
this it's got error 👆

and in lua table at start from 1
and table.sort work only from 1 ~ 2,3,4,5.6

please fix lua parse table start from 1....
or add Option to send from lua in the json...

**Comment by rizaumami** [comment]
@MyGitHub5 
Try @giuseppeM99 forks here: https://github.com/giuseppeM99/tdbot

**Comment by MyGitHub5** [comment]
Thanks!
it's works!!!

**Comment by giuseppeM99** [comment]
>Can't parse "9.2233720368548e+18" as number
The json parser treats numbers as lua_Number(s) [default dobule] max value 2^52, so 2^63 get approximated in an exponential form that then got parsed as a string, i'm going to fix this in my fork [note that this will only work on lua 5.3]
edit don't use exponential form, lua reads them as lua_Number(s)

>and please add if happens error still its call to callback...
done on my fork, going to push it, test it [missing time] and PR to vysheng

>postpone function it's very important....
I'll try

**Comment by MyGitHub5** [comment]
@giuseppeM99
https://github.com/vysheng/tdbot/issues/4#issuecomment-370295283 this fix "Can't parse "9.2233720368548e+18" as number"

**Comment by MyGitHub5** [comment]
@giuseppeM99 postpone it's ready?

**Comment by giuseppeM99** [comment]
I was working to other stuff

**Comment by SPY-Coder** [comment]
how do I find new TDbot variable and functions ?

**Comment by Unix-Coder** [comment]
Hello there
my lua source has been setted on " https://valtman.name/files/telegram-bot-180519-nightly-linux "
how do I find new TDbot variable and functions ?
